version: '3.8'

services:
  douyin-app:
    image: douyin-project-app:latest
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static  # 持久化静态文件
    depends_on:
      - db
      - redis
    environment:
      - TZ=Asia/Shanghai

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: douyin123
      MYSQL_DATABASE: douyin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
