apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: douyin-app
  name: douyin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: douyin-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: douyin-app
    spec:
      containers:
        - env:
            - name: TZ
              value: Asia/Shanghai
          image: douyin-project-app:latest
          imagePullPolicy: Never
          name: douyin-app
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/static
              name: douyin-app-claim0
      restartPolicy: Always
      volumes:
        - name: douyin-app-claim0
          persistentVolumeClaim:
            claimName: douyin-app-claim0
